name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_in_app_messaging:
    path: ../
  firebase_core: ^0.5.0-dev.2
  firebase_analytics: ^6.0.0-dev.1

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
