name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

dependencies:
  flutter:
    sdk: flutter

  firebase_dynamic_links:
    path: ../
  firebase_core: ^0.5.0-dev.2

  url_launcher: ^5.1.6

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
