name: cloud_functions
description: Flutter plugin for Cloud Functions.
version: 0.6.0-dev.2
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.cloudfunctions
        pluginClass: CloudFunctionsPlugin
      ios:
        pluginClass: CloudFunctionsPlugin
      macos:
        pluginClass: CloudFunctionsPlugin
      web:
        default_package: cloud_functions_web

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0-dev.1
  cloud_functions_platform_interface: ^2.0.0-dev.1
  cloud_functions_web: ^2.0.0-dev.1

dev_dependencies:
  pedantic: ^1.8.0
  firebase_core_platform_interface: ^2.0.0-dev.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'
