name: firebase_performance
description: Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance
version: 0.4.0-dev.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0-dev.1

dev_dependencies:
  pedantic: ^1.8.0
  http: ^0.12.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseperformance
        pluginClass: FirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
