name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 0.1.4+1
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.9.3

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  flutter_driver:
    sdk: flutter
  e2e: ^0.6.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics.firebasecrashlytics
        pluginClass: FirebaseCrashlyticsPlugin
      ios:
        pluginClass: FirebaseCrashlyticsPlugin
      macos:
        pluginClass: FirebaseCrashlyticsPlugin
