name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database
version: 4.0.0-dev.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin
      macos:
        pluginClass: FLTFirebaseDatabasePlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0-dev.1

dev_dependencies:
  firebase_core_platform_interface: ^2.0.0-dev.1
  pedantic: ^1.8.0
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
